name: d3f_networking
version: 1.0.0+1
publish_to: none
description: d3f_networking.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  d3f_dependency_manager: 
    git: 
      url: https://github.com/DanhDue-ExOICTIF/d3f_dependency_manager.git
      ref: develop

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.10+1
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  hive_generator: ^1.1.3
  freezed: ^2.1.0+1
  flutter_test: 
    sdk: flutter

flutter: 
  module: 
    androidPackage: com.danhdue.d3f_networking
    iosBundleIdentifier: com.danhdue.d3fNetworking
    androidX: true
  uses-material-design: true

